INSERT INTO users (id, name, password, role, fullname, resPw) VALUES (1, 'admin','', 0, 'Administrator',1);
INSERT INTO utils (id, abbr, name, value, text, typ) VALUES (1,'USt','Umsatzsteuer',19,'Umsatzsteuerwert für Leistungen','K'),
(2,'Sk','Skonto',3,'Preisnachlass für schnelle Bezahlung der Rechung','K'),
(3,'MGK','Materialgemeinkosten',1,'Lagerkosten, Transportkosten, Prüfkosten, Kleinteile...','K'),
(4,'FGK','Fertigungsgemeinkosten',1,'Restgemeinkosten wie Hilfslöhne, Sozialkosten...','K'),
(5,'VWGK','Verwaltungsgemeinkosten',1,'Buchhaltung, Angebote, Dokumentation...','K'),
(6,'VTGK','Vertriebgemeinkosten',1,'Werbung, Newsletter...','K'),
(7,'FAL','Facharbeiterlohn',1,'Facharbeiterlohn in €/h','K'),
(8,'WG','Wagnis/Gewinn',1,'Globaler, %-er Wert für Risiko + Gewinnschöpfung','K'),
(9,'MRab','Max Rabatt',1,'Maximaler zulaessiger Rabatt','K'),
(10,'RabAlle','Rabatt Alle',1,'Globaler Wert für alle Kunden','R'),
(11,'RabOeff','Rabatt Öffentlich',1,'Globaler Wert für alle Kunden des Typs Öffentlich','R'),
(12,'RabFi','Rabatt Firma',1,'Globaler Wert für alle Kunden des Typs Firma','R'),
(13,'RabPriv','Rabatt Privat',1,'Globaler Wert für alle Kunden des Typs Privat','R'),
(14,'RabAlleS','Rabatt Alle Status',0,'0 inaktiv,  1 aktiv','R'),
(15,'RabOeffS','Rabatt Öffentlich Status',0,'0 inaktiv, 1 aktiv','R'),
(16,'RabFiS','Rabatt Firma Status',0,'0 inakitv, 1 aktiv','R'),
(17,'RabPrivS','Rabatt Privat Status',0,'0 inaktiv, 1 aktiv','R'),
(18,'KNR','Max Kundennummer',2017010001,'Hoechste bekannte Kundennummer','N'),
(19,'PNR','Max Produktnummer',2017010001,'Hoechste bekannte Produktnummer','N'),
(20,'ANR','Max Auftragsnummer',2017010001,'Hoechste bekannte Auftragsnummer','N');